-- MySQL Script generated by MySQL Workbench
-- Fri Oct 31 14:46:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alunos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alunos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alunos` DEFAULT CHARACTER SET utf8 ;
USE `alunos` ;

-- -----------------------------------------------------
-- Table `alunos`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alunos`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `curso` VARCHAR(45) NULL,
  `idade` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `alunos`.`aluno` (`nome`, `curso`, `idade`) VALUES ('Natan', 'Info', '18');
INSERT INTO `alunos`.`aluno` (`nome`, `curso`, `idade`) VALUES ('Douglas', 'Elec', '18');
INSERT INTO `alunos`.`aluno` (`nome`, `curso`, `idade`) VALUES ('Zenon', 'Pub', '17');
INSERT INTO `alunos`.`aluno` (`nome`, `curso`, `idade`) VALUES ('Jefferson', 'Adm', '17');
INSERT INTO `alunos`.`aluno` (`nome`, `curso`, `idade`) VALUES ('Lucas', 'Qui', '17');
